### ISSUE TITLE
messwithdns.com missing NS records

### ISSUE THREAD

**Issue by hvenev** [jvns/mess-with-dns-backend#4]
```
$ dig ns messwithdns.com @d.gtld-servers.com
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 53067
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 2, ADDITIONAL: 5

;; AUTHORITY SECTION:
messwithdns.com.	172800	IN	NS	mess-with-dns1.wizardzines.com.
messwithdns.com.	172800	IN	NS	mess-with-dns2.wizardzines.com.

;; ADDITIONAL SECTION:
mess-with-dns1.wizardzines.com.	172800 IN A	213.188.214.237
mess-with-dns1.wizardzines.com.	172800 IN AAAA	2a09:8280:1::a:b31
mess-with-dns2.wizardzines.com.	172800 IN A	213.188.214.254
mess-with-dns2.wizardzines.com.	172800 IN AAAA	2a09:8280:1::a:b31
```

```
$ dig ns messwithdns.com @213.188.214.237
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 61947
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; AUTHORITY SECTION:
messwithdns.com.	300	IN	SOA	ns1.messwithdns.com. julia.wizardzines.com. 2847 3600 3600 7300 3600
```

The answer given by `213.188.214.237` seems to be very inconsistent. It claims `NXDOMAIN` for `messwithdns.com`, i.e. there aren't any records of any type for that name, but then also provides a SOA record for the same name in the authority section.

**Comment by jvns** [comment]
Should be fixed now, thanks!


```
$ dig ns messwithdns.com @213.188.214.237
messwithdns.com.	60	IN	NS	mess-with-dns1.wizardzines.com.
messwithdns.com.	60	IN	NS	mess-with-dns2.wizardzines.com.
```

**Comment by hvenev** [comment]
NS records still don't show up when the query uses upper case. This means that it's incompatible with resolvers that implement dns-0x20.
